/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as BootRouteImport } from './routes/boot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOnboardingVerifyRouteImport } from './routes/_authenticated/onboarding.verify'
import { Route as AuthenticatedOnboardingAvatradeRouteImport } from './routes/_authenticated/onboarding.avatrade'
import { Route as AuthenticatedChallengesNewRouteImport } from './routes/_authenticated/challenges.new'
import { Route as AuthenticatedChallengesIdRouteImport } from './routes/_authenticated/challenges.$id'
import { Route as ApiPublicCardUsernameRouteImport } from './routes/api/public/card.$username'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingVerifyRoute =
  AuthenticatedOnboardingVerifyRouteImport.update({
    id: '/onboarding/verify',
    path: '/onboarding/verify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAvatradeRoute =
  AuthenticatedOnboardingAvatradeRouteImport.update({
    id: '/onboarding/avatrade',
    path: '/onboarding/avatrade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesNewRoute =
  AuthenticatedChallengesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const AuthenticatedChallengesIdRoute =
  AuthenticatedChallengesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const ApiPublicCardUsernameRoute = ApiPublicCardUsernameRouteImport.update({
  id: '/api/public/card/$username',
  path: '/api/public/card/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boot': typeof BootRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-demo': typeof LiveDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live/$id': typeof LiveIdRoute
  '/u/$username': typeof UUsernameRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/onboarding/avatrade': typeof AuthenticatedOnboardingAvatradeRoute
  '/onboarding/verify': typeof AuthenticatedOnboardingVerifyRoute
  '/api/public/card/$username': typeof ApiPublicCardUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boot': typeof BootRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-demo': typeof LiveDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live/$id': typeof LiveIdRoute
  '/u/$username': typeof UUsernameRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/onboarding/avatrade': typeof AuthenticatedOnboardingAvatradeRoute
  '/onboarding/verify': typeof AuthenticatedOnboardingVerifyRoute
  '/api/public/card/$username': typeof ApiPublicCardUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/boot': typeof BootRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-demo': typeof LiveDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/live/$id': typeof LiveIdRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/_authenticated/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/_authenticated/onboarding/avatrade': typeof AuthenticatedOnboardingAvatradeRoute
  '/_authenticated/onboarding/verify': typeof AuthenticatedOnboardingVerifyRoute
  '/api/public/card/$username': typeof ApiPublicCardUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boot'
    | '/leaderboard'
    | '/live-demo'
    | '/reset-password'
    | '/admin'
    | '/challenges'
    | '/dashboard'
    | '/live/$id'
    | '/u/$username'
    | '/challenges/$id'
    | '/challenges/new'
    | '/onboarding/avatrade'
    | '/onboarding/verify'
    | '/api/public/card/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/boot'
    | '/leaderboard'
    | '/live-demo'
    | '/reset-password'
    | '/admin'
    | '/challenges'
    | '/dashboard'
    | '/live/$id'
    | '/u/$username'
    | '/challenges/$id'
    | '/challenges/new'
    | '/onboarding/avatrade'
    | '/onboarding/verify'
    | '/api/public/card/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/boot'
    | '/leaderboard'
    | '/live-demo'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/live/$id'
    | '/u/$username'
    | '/_authenticated/challenges/$id'
    | '/_authenticated/challenges/new'
    | '/_authenticated/onboarding/avatrade'
    | '/_authenticated/onboarding/verify'
    | '/api/public/card/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootRoute: typeof BootRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveDemoRoute: typeof LiveDemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LiveIdRoute: typeof LiveIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicCardUsernameRoute: typeof ApiPublicCardUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/verify': {
      id: '/_authenticated/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof AuthenticatedOnboardingVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/avatrade': {
      id: '/_authenticated/onboarding/avatrade'
      path: '/onboarding/avatrade'
      fullPath: '/onboarding/avatrade'
      preLoaderRoute: typeof AuthenticatedOnboardingAvatradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/new': {
      id: '/_authenticated/challenges/new'
      path: '/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof AuthenticatedChallengesNewRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/_authenticated/challenges/$id': {
      id: '/_authenticated/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof AuthenticatedChallengesIdRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/api/public/card/$username': {
      id: '/api/public/card/$username'
      path: '/api/public/card/$username'
      fullPath: '/api/public/card/$username'
      preLoaderRoute: typeof ApiPublicCardUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChallengesRouteChildren {
  AuthenticatedChallengesIdRoute: typeof AuthenticatedChallengesIdRoute
  AuthenticatedChallengesNewRoute: typeof AuthenticatedChallengesNewRoute
}

const AuthenticatedChallengesRouteChildren: AuthenticatedChallengesRouteChildren =
  {
    AuthenticatedChallengesIdRoute: AuthenticatedChallengesIdRoute,
    AuthenticatedChallengesNewRoute: AuthenticatedChallengesNewRoute,
  }

const AuthenticatedChallengesRouteWithChildren =
  AuthenticatedChallengesRoute._addFileChildren(
    AuthenticatedChallengesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingAvatradeRoute: typeof AuthenticatedOnboardingAvatradeRoute
  AuthenticatedOnboardingVerifyRoute: typeof AuthenticatedOnboardingVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingAvatradeRoute: AuthenticatedOnboardingAvatradeRoute,
  AuthenticatedOnboardingVerifyRoute: AuthenticatedOnboardingVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BootRoute: BootRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveDemoRoute: LiveDemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LiveIdRoute: LiveIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicCardUsernameRoute: ApiPublicCardUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
